openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: weather
    description: В этом разделе можно получить сведение о погоде в желаемом городе
paths:
  /weather/{cityName}:
    get:
      tags:
        - weather
      summary: Получить погоду по его названию
      operationId: getWeather
      parameters:
        - name: cityName
          in: path
          description: Название города
          required: true
          schema:
            type: string
          example: Санкт-Петербург
        - name: serviceName
          in: query
          description: Название сервиса погоды
          required: false
          schema:
            type: string
          example: yandexweather
      responses:
        '200':
          description: Все прошло успешно, город найден
          content:
            application/json:
              schema:
                type: string
                example:
                  City: Санкт-Петербург
                  lat: '59.938732'
                  lon: '30.316229'
                  weather:
                    temperature: '24.43'
                    condition: ясно
        '400':
          description: Unknown service name
        '404':
          description: Incorrect city name
components: {}
